name: Test Coveralls Parallel

on:
  - pull_request
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name:
          - Node.js 18.x

        include:
          - name: Node.js 18.x
            node-version: '18.0'

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js ${{ matrix.node-version }}
        shell: bash -eo pipefail -l {0}
        run: |
          nvm install --default ${{ matrix.node-version }}
          if [[ "${{ matrix.node-version }}" == 0.* && "$(cut -d. -f2 <<< "${{ matrix.node-version }}")" -lt 10 ]]; then
            nvm install --alias=npm 0.10
            nvm use ${{ matrix.node-version }}
            sed -i '1s;^.*$;'"$(printf '#!%q' "$(nvm which npm)")"';' "$(readlink -f "$(which npm)")"
            npm config set strict-ssl false
          fi
          dirname "$(nvm which ${{ matrix.node-version }})" >> "$GITHUB_PATH"

      - name: Configure npm
        run: npm config set shrinkwrap false

      - name: Remove npm module(s) ${{ matrix.npm-rm }}
        run: npm rm --silent --save-dev ${{ matrix.npm-rm }}
        if: matrix.npm-rm != ''

      - name: Install npm module(s) ${{ matrix.npm-i }}
        run: npm install --save-dev ${{ matrix.npm-i }}
        if: matrix.npm-i != ''

      - name: Install Node.js dependencies
        run: npm install

      - name: List environment
        id: list_env
        shell: bash
        run: |
          echo "node@$(node -v)"
          echo "npm@$(npm -v)"
          npm -s ls ||:
          (npm -s ls --depth=0 ||:) | awk -F'[ @]' 'NR>1 && $2 { print "::set-output name=" $2 "::" $3 }'

      - name: Run tests
        shell: bash
        run: npm test

      - name: Lint code
        run: npm run lint

      - name: Collect code coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: run-${{ matrix.test_number }}
          parallel: true
          path-to-lcov: ./coverage/lcov.info

  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Upload code coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
